### ISSUE TITLE
JBAS014793: No known child type named host

### ISSUE THREAD

**Issue by zhimiaoli** [marcanpilami/Zabbix-JBoss-Agent#2]
hi, I config the application and started without any error., and jboss as 7.2.0 run in standalone mode,,

but jboss as prompt this error?
11:19:01,011 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) JBAS014613: Operation ("read-children-names") failed - address: ([]) - failure description: "JBAS014793: No known child type named host"

how can I fix this? thanks a lot.

**Comment by marcanpilami** [comment]
Hi, 

the issue is that the default configuration of monitored items (items.txt) is for a domain install of JBoss. You are clearly using a single node install, so there is no /host= configuration item. You will need to configure the items according to this. I believe mostly removing the /host=.../ will be enough in most cases.

If you go this route, it would be really appreciated if you could contribute your items.txt afterwards, to help others with the same need.
